### ISSUE TITLE
Switch_switch_grpc compilation error

### ISSUE THREAD

**Issue by WQQ0921** [p4lang/behavioral-model#969]
/usr/local/lib/libpi.so: undefined reference to `_pi_table_entry_get_remaining_ttl'
/usr/local/lib/libpi.so: undefined reference to `_pi_clone_session_reset'
/usr/local/lib/libpi.so: undefined reference to `_pi_mc_grp_detach_node'
/usr/local/lib/libpi.so: undefined reference to `_pi_act_prof_grp_set_mbrs'
/usr/local/lib/libpi.so: undefined reference to `_pi_clone_session_set'
/usr/local/lib/libpi.so: undefined reference to `_pi_mc_grp_attach_node'
/usr/local/lib/libpi.so: undefined reference to `_pi_table_idle_timeout_config_set'
collect2: error: ld returned 1 exit status
Makefile:717: recipe for target 'simple_switch_grpc' failed
make[2]: *** [simple_switch_grpc] Error 1

Dependencies are installed, GRPC, BM2V are installed.
I don't know how to solve it, please help me.

**Comment by jafingerhut** [comment]
I do not know what steps you followed, but I have recently tested the script described at the following link on Ubuntu 16.04 and Ubuntu 18.04 Linux systems, freshly installed with no other additional software installed on them yet, and it compiled and installed the latest version of the behavioral-model code, and the p4c compiler, Thrift, gRPC, mininet, etc.  https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md

**Comment by WQQ0921** [comment]
I installed it in accordance with the official document. When I finally installed the SWITCH_GRPC of the BM2V switch, make did not pass and the error was always reported. I don't know why

**Comment by WQQ0921** [comment]
> I do not know what steps you followed, but I have recently tested the script described at the following link on Ubuntu 16.04 and Ubuntu 18.04 Linux systems, freshly installed with no other additional software installed on them yet, and it compiled and installed the latest version of the behavioral-model code, and the p4c compiler, Thrift, gRPC, mininet, etc. https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md

I installed it in accordance with the official document. When I finally installed the SWITCH_GRPC of the BM2V switch, make did not pass and the error was always reported. I don't know why

**Comment by jafingerhut** [comment]
I do not know whether you noticed the README in this directory, which mentions extra software that must be installed before you can build simple_switch_grpc: https://github.com/p4lang/behavioral-model/tree/master/targets/simple_switch_grpc

In any case, it is possible that the README instructions are incomplete.  You are welcome to struggle through the READMEs and experiment a lot, or you can take advantage of the many hours I spent experimenting to find a working recipe in the script that I linked to the instructions for.  Your choice.

**Comment by antoninbas** [comment]
This could be many things but my guess would be that you didn't run `./configure` with `--with-pi`, or that for some other reason that code didn't get built.

If you don't want to spend too much time on this, I would recommend following @jafingerhut's suggestion

**Comment by WQQ0921** [comment]
I've executed the. Configure --with-pi command. Every previous step makes check to pass. But in the last step of installing the module, make reports an error.

**Comment by WQQ0921** [comment]
> This could be many things but my guess would be that you didn't run `./configure` with `--with-pi`, or that for some other reason that code (https://github.com/p4lang/behavioral-model/tree/master/PI) didn't get built.
> 
> If you don't want to spend too much time on this, I would recommend following @jafingerhut's suggestion

I've executed the. Configure --with-pi command. Every previous step makes check to pass. But in the last step of installing the module, make reports an error.

**Comment by jafingerhut** [comment]
@WQQ0921 What is your goal here?

If it is to get a working system with all of the open source P4 development tools for yourself, and to start using it as soon as possible, then I'd recommend following the instructions I linked before: https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md

If your goal is instead to determine in what way the README instructions you have followed might be missing something, that is a potentially much more time consuming goal.  The way I would recommend determining that is to follow along in the README instructions you can find, and carefully compare them to the steps in a script that I have tested works on Ubuntu 16.04 and 18.04 Linux systems here, and suggest changes to the README if they are ever lacking a step: https://github.com/jafingerhut/p4-guide/blob/master/bin/install-p4dev-v2.sh

If your goal is something else, describe what it is, and we can consider whether we know how to help you achieve it.

**Comment by WQQ0921** [comment]
> @WQQ0921 What is your goal here?
> 
> If it is to get a working system with all of the open source P4 development tools for yourself, and to start using it as soon as possible, then I'd recommend following the instructions I linked before: https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md
> 
> If your goal is instead to determine in what way the README instructions you have followed might be missing something, that is a potentially much more time consuming goal. The way I would recommend determining that is to follow along in the README instructions you can find, and carefully compare them to the steps in a script that I have tested works on Ubuntu 16.04 and 18.04 Linux systems here, and suggest changes to the README if they are ever lacking a step: https://github.com/jafingerhut/p4-guide/blob/master/bin/install-p4dev-v2.sh
> 
> If your goal is something else, describe what it is, and we can consider whether we know how to help you achieve it.

[MAKE] Generating cache.mk
[C] Compiling src/boringssl/err_data.c
src/boringssl/err_data.c:22:37: error: expected ‘)’ before ‘==’ token
OPENSSL_COMPILE_ASSERT(ERR_LIB_NONE == 1, library_values_changed_1);
^
src/boringssl/err_data.c:23:36: error: expected ‘)’ before ‘==’ token
OPENSSL_COMPILE_ASSERT(ERR_LIB_SYS == 2, library_values_changed_2);
^
src/boringssl/err_data.c:24:35: error: expected ‘)’ before ‘==’ token
OPENSSL_COMPILE_ASSERT(ERR_LIB_BN == 3, library_values_changed_3);
^
src/boringssl/err_data.c:25:36: error: expected ‘)’ before ‘==’ token
OPENSSL_COMPILE_ASSERT(ERR_LIB_RSA == 4, library_values_changed_4);

s_changed_5);

Follow your method,but an error was reported when compling grpc.

**Comment by jafingerhut** [comment]
No follow up up on desired goals for 8 months.  Seems worth closing the issue.
